#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Husky.Net - https://alirezanet.github.io/Husky.Net/guide/#features
# post-commit - https://git-scm.com/docs/githooks#_post_commit

echo
echo '***************'
echo '* post-commit *'
echo '***************'
echo
