#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Husky.Net - https://alirezanet.github.io/Husky.Net/guide/#features
# pre-commit - https://git-scm.com/docs/githooks#_pre_commit

## husky task runner examples -------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands -------------------
#echo 'Husky.Net is awesome!'

echo
echo '**************'
echo '* pre-commit *'
echo '**************'

echo 'Welcome to the BrandsMart project!'
echo
